In [17]:
import tensorflow as tf

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import pandas as pd


In [18]:
%matplotlib inline

In [19]:
a = tf.constant(2)
b = tf.constant(3)

In [20]:
mat1 = tf.constant([[1,3,2],
                    [1,0,0],
                    [1,2,2]])

mat2 = tf.constant([[1,0,5],
                    [7,5,0],
                    [2,1,1]])

In [21]:
suma = tf.add(a, b)
mult = tf.multiply(a, b)
cubo = a**3

mat_sum = tf.add(mat1, mat2)

mat_mul = tf.matmul(mat1, mat2)

In [22]:
with tf.Session() as sess:
    print('Suma de constantes: {}'.format(sess.run(suma)))
    print('Multiplicacion de constantes: {}'.format(sess.run(mult)))
    print('cte al cubo: {}'.format(sess.run(cubo)))
    print('Suma de matrices: \n{}'.format(sess.run(mat_sum)))
    print('Producto de constantes: \n{}'.format(sess.run(mat_mul)))

Suma de constantes: 5
Multiplicacion de constantes: 6
cte al cubo: 8
Suma de matrices: 
[[2 3 7]
 [8 5 0]
 [3 3 3]]
Producto de constantes: 
[[26 17  7]
 [ 1  0  5]
 [19 12  7]]


In [23]:
estado = tf.Variable(0, name = "contador")

uno = tf.constant(1)
nuevo_valor = tf.add(estado, uno)
actualizar = tf.assign(estado, nuevo_valor)

init = tf.global_variables_initializer()

In [24]:
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(estado))
    
    for _ in range(3):
        sess.run(actualizar)
        print(sess.run(estado))

0
1
2
3


In [25]:
x = tf.placeholder(tf.float32, shape=(4,4))
y = tf.matmul(x,x)


In [26]:
with tf.Session() as sess:
    rand_array = np.random.rand(4,4)
    print(sess.run(y,feed_dict={x:rand_array}))

[[ 0.74455178  2.04502082  1.29145956  1.92700863]
 [ 0.48550126  1.43858564  0.88412744  1.57123566]
 [ 0.31151772  1.4675616   1.05385756  1.14402235]
 [ 0.51306152  1.51764846  0.95812404  1.54412639]]


In [27]:
#MI PRIMERA NEURONA --> AND
#Entradas
entradas = tf.placeholder('float', name = 'entradas')
datos = np.array([[0,0]
                 ,[1,0]
                 ,[0,1]
                 ,[1,1]])

#Salidas
uno = lambda: tf.constant(1.0)
cero = lambda:tf.constant(0.0)

#Pesos y bias
with tf.name_scope('Pesos'):
    pesos = tf.placeholder('float', name = 'pesos')
    bias = tf.placeholder('float', name = 'bias')

    
#Funcion de activacion de la neurona
with tf.name_scope('Activacion'):
    activacion = tf.reduce_sum(tf.add(tf.matmul(entradas, pesos),bias))
    

#Neurona
with tf.name_scope('Neurona'):
    def neurona():
        return tf.case([(tf.less(activacion, 0.0),cero)],default = uno)
    
    #Salida de la neurona
    a = neurona
    
#Logs
logs_path = '/tmp/tensorflow_logs/neurona'

In [39]:
#Lanzamos la sesion
#Neurona AND
with tf.Session() as sess:
    #Armamos el grafo
    summary_writter = tf.summary.FileWriter(logs_path,
                                             graph = sess.graph)
    
    #Armamos la tabla de verdad
    
    x_1 = []
    x_2 = []
    out = []
    act = []
    
    for i in range (len(datos)):
        t = datos[i].reshape(1,2)
        salida, activ = sess.run([a(), activacion], feed_dict = {entradas: t,
                                                              pesos : np.array([[1.],[1.]]),
                                                              bias: -1.5})
        
        #Armar la tabla de verdad en DataFrame
        
        x_1.append(t[0][0])
        x_2.append(t[0][1])
        out.append(salida)
        act.append(activ)
    
    tabla_info = np.array([x_1, x_2, act, out]).transpose()
    tabla = pd.DataFrame(tabla_info,columns=['x1', 'x2', 'f(x)', 'x1 AND x2'])
    
tabla
    

x1   x2  f(x)  x1 AND x2
0  0.0  0.0  -1.5        0.0
1  1.0  0.0  -0.5        0.0
2  0.0  1.0  -0.5        0.0
3  1.0  1.0   0.5        1.0

In [40]:
#Lanzamos la sesion
#Neurona OR
with tf.Session() as sess:
    #Armamos el grafo
    summary_writter = tf.summary.FileWriter(logs_path,
                                             graph = sess.graph)
    
    #Armamos la tabla de verdad
    
    x_1 = []
    x_2 = []
    out = []
    act = []
    
    for i in range (len(datos)):
        t = datos[i].reshape(1,2)
        salida, activ = sess.run([a(), activacion], feed_dict = {entradas: t,
                                                              pesos : np.array([[1.],[1.]]),
                                                              bias: -0.5})
        
        #Armar la tabla de verdad en DataFrame
        
        x_1.append(t[0][0])
        x_2.append(t[0][1])
        out.append(salida)
        act.append(activ)
    
    tabla_info = np.array([x_1, x_2, act, out]).transpose()
    tabla = pd.DataFrame(tabla_info,columns=['x1', 'x2', 'f(x)', 'x1 OR x2'])
    
tabla
    

x1   x2  f(x)  x1 OR x2
0  0.0  0.0  -0.5       0.0
1  1.0  0.0   0.5       1.0
2  0.0  1.0   0.5       1.0
3  1.0  1.0   1.5       1.0